# Trading Bot Configuration

# Binance API Settings
binance:
  api_key: "your_api_key"
  api_secret: "your_api_secret"
  testnet: true  # Set to false for live trading

# Telegram Settings
telegram:
  token: "7966861727:AAHE-TDH2sZNxWhwRSZO2B48-4cKP6cuCE0"
  chat_id: "5184726235"

# WebSocket Settings  
websocket:
  host: "localhost"
  port: 8765

# Trading Parameters
trading:
  # Minimum 24h USDT volume for trading pairs
  min_volume: 1000000  # $1M USD
  
  # Maximum number of concurrent trades
  max_trades: 5
  
  # Order size in USDT
  order_size: 100
  
  # Risk management
  max_loss_percent: 2.0  # Maximum loss per trade
  daily_loss_limit: 5.0  # Maximum daily loss
  
  # Take profit and stop loss defaults
  default_tp_percent: 1.0
  default_sl_percent: 0.5

# Signal Detection
signals:
  # Timeframes to scan
  timeframes:
    - "1m"
    - "5m"
    - "15m"
    - "1h"
    - "4h"
    
  # Minimum confidence score (0-100)
  min_confidence: 70
  
  # Technical indicators
  rsi_period: 14
  fast_ma: 12
  slow_ma: 26
  volume_period: 20
  
  # Volume requirements
  volume_ratio_min: 1.5  # Minimum volume vs average

# GUI Settings
gui:
  # Update interval in milliseconds
  update_interval: 1000
  
  # Colors
  colors:
    profit: "#4CAF50"
    loss: "#F44336"
    neutral: "#9E9E9E"

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s UTC | %(levelname)s | %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"