# Bot Configuration
testnet: true

# Binance Testnet API Configuration - API key mới từ testnet.binance.vision
api_key: "6ef4e6c3e0a73ab6175a7bb4322556a76424e46d598324b20e9dcd88557a2293"
api_secret: "0e34e4c06103ba07575f59816aa3e061f5635dec472dcd81c9c3143cefdda2aa"

# Telegram Configuration 
telegram_token: "7966861727:AAHE-TDH2sZNxWhwRSZO2B48-4cKP6cuCE0"
telegram_chat_id: "5184726235"

# Trading Configuration
min_volume: 1000000
min_confidence: 70
timeframes:
  - "1m"
  - "5m" 
  - "15m"
  - "1h"
  - "4h"

# Order Configuration  
order_size: 100
max_orders: 10
risk_per_trade: 1

# GUI Configuration
gui_enabled: true
gui_update_interval: 1

# WebSocket Configuration
ws_host: "localhost"
ws_port: 8765